#!/usr/bin/env bash
# Regenerate STATUS.md from EPIC-*/epic.md and EPIC-*/STORY-*.md.
# Tasks are GitHub-style checkboxes (- [ ] / - [x]) inside story files; their
# counts drive the progress bars. Do not edit STATUS.md by hand.
#
#   ./cockpit.sh            # write STATUS.md
#   ./cockpit.sh --stdout   # print to stdout instead
set -euo pipefail
cd "$(dirname "$0")"

field() { grep -m1 "^$2:" "$1" 2>/dev/null | sed "s/^$2:[[:space:]]*//" | tr -d '\r'; }

checks() { # file -> "done total"
  local d t
  d=$(grep -cE '^[[:space:]]*- \[[xX]\]' "$1" 2>/dev/null || true)
  t=$(grep -cE '^[[:space:]]*- \[[ xX]\]' "$1" 2>/dev/null || true)
  echo "${d:-0} ${t:-0}"
}

bar() { # done total -> "███░░░░░░░ 30% (3/10)"
  local done=$1 total=$2 pct filled i b=""
  if [ "$total" -eq 0 ]; then pct=0; else pct=$(( done * 100 / total )); fi
  filled=$(( pct / 10 ))
  for ((i=0; i<10; i++)); do [ $i -lt $filled ] && b+="█" || b+="░"; done
  printf '%s %d%% (%d/%d)' "$b" "$pct" "$done" "$total"
}

emit() {
  local gtot=0 gdone=0
  echo "# midi-maze-js Cockpit"
  echo
  echo "_Generated by \`docs/epics/cockpit.sh\`. Do not edit by hand._"
  echo

  # Discover iterations present across epics, sorted.
  local iters
  iters=$(for e in EPIC-*/epic.md; do [ -f "$e" ] && field "$e" iteration; done | sort -un)

  local body="" it
  for it in $iters; do
    body+=$'\n'"## Iteration $it"$'\n'
    local e
    for e in EPIC-*/epic.md; do
      [ -f "$e" ] || continue
      [ "$(field "$e" iteration)" = "$it" ] || continue
      local dir id title estatus edone=0 etot=0
      dir=$(dirname "$e")
      id=$(field "$e" id); title=$(field "$e" title); estatus=$(field "$e" status)
      local s
      for s in "$dir"/STORY-*.md; do
        [ -f "$s" ] || continue
        read -r sd st < <(checks "$s")
        edone=$(( edone + sd )); etot=$(( etot + st ))
      done
      gdone=$(( gdone + edone )); gtot=$(( gtot + etot ))
      body+=$'\n'"### $id · $title"$'\n'
      body+="\`$estatus\` $(bar "$edone" "$etot")"$'\n'
      for s in "$dir"/STORY-*.md; do
        [ -f "$s" ] || continue
        read -r sd st < <(checks "$s")
        body+="- **$(field "$s" id)** $(field "$s" title) — \`$(field "$s" status)\` [$sd/$st]"$'\n'
      done
    done
  done

  echo "**Overall:** $(bar "$gdone" "$gtot")"
  echo "$body"
}

if [ "${1:-}" = "--stdout" ]; then emit; else emit > STATUS.md; echo "wrote STATUS.md"; fi
